image:
  file: .gitpod/Dockerfile

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
    - redhat.vscode-yaml
    - skellock.just

tasks:
  - init: |
      pip3 install -r requirements.txt

ports:
  - port: 5000
    onOpen: open-browser
